- name: Copy private key to server
  ansible.builtin.copy:
    src: "{{ lookup('file', './files/keys/{{ git_private_key }}') }}"
    dest: "/home/{{ app_user }}/.ssh/id_app"
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: "0600"

- name: Ensure project directory is exist
  ansible.builtin.file:
    path: "{{ project_path }}"
    state: directory
    mode: '0755'

- name: Clone Laravel repository
  ansible.builtin.git:
    repo: "{{ git_repo }}"
    dest: "{{ project_path }}"
    version: "{{ git_branch }}"
    single_branch: true

- name: Install Laravel dependencies
  ansible.builtin.command:
  cmd: composer install --no-dev --prefer-dist
  args:
    chdir: /var/www/laravel
  register: composer_output
  changed_when: composer_output.rc != 0

- name: Copy .env.example to .env
  ansible.builtin.copy:
    src: /var/www/laravel/.env.example
    dest: /var/www/laravel/.env
    remote_src: true
    mode: "0644"

- name: Generate application key
  ansible.builtin.command: php artisan key:generate
  args:
    chdir: /var/www/laravel
  register: key_output
  changed_when: key_output.rc != 0

- name: Edit .env with the correct value
  ansible.builtin.lineinfile:
    dest: "{{ project_path }}/.env"
    state: present
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^DB_HOST', line: 'DB_HOST=127.0.0.1'}
    - { regexp: '^DB_DATABASE', line: 'DB_DATABASE={{ mariadb.db_name }}'}
    - { regexp: '^DB_USERNAME', line: 'DB_USERNAME={{ mariadb.db_user }}'}
    - { regexp: '^DB_PASSWORD', line: 'DB_PASSWORD={{ mariadb.db_pass }}'}

- name: Running Migrations
  ansible.builtin.command:
    cmd: php artisan migrate
  register: migrate_output
  changed_when: migrate_output.rc != 0
