- name: Install Nginx
  ansible.builtin.dnf:
    name: nginx
    state: present

- name: Ensure Nginx service is running and enabled
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true

- name: Remove default Nginx configuration
  ansible.builtin.file:
    path: /etc/nginx/conf.d/default.conf
    state: absent

- name: Create Nginx configuration for Laravel
  ansible.builtin.template:
    src: nginx_laravel.conf.j2
    dest: /etc/nginx/conf.d/laravel.conf
    mode: "0644"
  notify: Restart Nginx
